### PR TITLE
fix julia language server for *nix

### LINKED ISSUE #280: julia language server does not launch
It seems that julia language server does not launch correctly.

This is lsp log file content:
```
Wed Jul 15 22:31:06 2020:["Starting server","julia-language-server",["/Users/home/.local/share/vim-lsp-settings/servers/julia-language-server/julia-language-server"]]
Wed Jul 15 22:31:06 2020:[{"response":{"data":{"__data__":"vim-lsp","lsp_id":1,"server_name":"julia-language-server"},"message":"started lsp server successfully"}}]
Wed Jul 15 22:31:06 2020:["--->",1,"julia-language-server",{"method":"initialize","params":{"rootUri":"file:////Users/home/Program/julia/test.jl","initializationOptions":null,"capabilities":{"workspace":{"configuration":true,"applyEdit":true},"textDocument":{"implementation":{"linkSupport":true},"documentSymbol":{"symbolKind":{"valueSet":[10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,1,2,3,4,5,6,7,8,9]},"hierarchicalDocumentSymbolSupport":false},"semanticHighlightingCapabilities":{"semanticHighlighting":false},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dynamicRegistration":false},"completion":{"completionItem":{"snippetSupport":false,"documentationFormat":["plaintext"]},"completionItemKind":{"valueSet":[10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,1,2,3,4,5,6,7,8,9]}},"foldingRange":{"lineFoldingOnly":true},"typeDefinition":{"linkSupport":true},"typeHierarchy":false,"declaration":{"linkSupport":true},"definition":{"linkSupport":true}}},"rootPath":"/Users/home/Program/julia/test.jl","processId":86430,"trace":"off"}}]
Wed Jul 15 22:31:09 2020:["s:send_event_queue()"]
Wed Jul 15 22:31:09 2020:["<---(stderr)",1,"julia-language-server",["ERROR: "]]
Wed Jul 15 22:31:09 2020:["<---(stderr)",1,"julia-language-server",["LoadError: "]]
Wed Jul 15 22:31:10 2020:["<---(stderr)",1,"julia-language-server",["MethodError: Cannot `convert` an object of type Bool to an object of type String","Closest candidates are:","  convert(::Type{String}, !Matched::FilePathsBase.AbstractPath) at /Users/home/.julia/packages/FilePathsBase/7ekFM/src/path.jl:107","  convert(::Type{T}, !Matched::T) where T<:AbstractString at strings/basic.jl:209","  convert(::Type{T}, !Matched::AbstractString) where T<:AbstractString at strings/basic.jl:210","  ..."]]
Wed Jul 15 22:31:10 2020:["<---(stderr)",1,"julia-language-server",["","Stacktrace:"]]
Wed Jul 15 22:31:10 2020:["<---(stderr)",1,"julia-language-server",["",""]]
Wed Jul 15 22:31:10 2020:["<---(stderr)",1,"julia-language-server",[" [1] "]]
Wed Jul 15 22:31:10 2020:["<---(stderr)",1,"julia-language-server",["LanguageServer.LanguageServerInstance"]]
Wed Jul 15 22:31:10 2020:["<---(stderr)",1,"julia-language-server",["("]]
Wed Jul 15 22:31:11 2020:["<---(stderr)",1,"julia-language-server",["::"]]
Wed Jul 15 22:31:11 2020:["<---(stderr)",1,"julia-language-server",["Base"]]
Wed Jul 15 22:31:11 2020:["<---(stderr)",1,"julia-language-server",[".PipeEndpoint, ::Base.PipeEndpoint, ::Bool, ::String, ::Nothing, ::Nothing) at /Users/atsushisakai/.julia/packages/LanguageServer/Fh5Xh/src/languageserverinstance.jl:66"]]
Wed Jul 15 22:31:11 2020:["<---(stderr)",1,"julia-language-server",[" (repeats "]]
Wed Jul 15 22:31:11 2020:["<---(stderr)",1,"julia-language-server",["2"]]
Wed Jul 15 22:31:11 2020:["<---(stderr)",1,"julia-language-server",[" times)"," [2] top-level scope at /Users/home/.local/share/vim-lsp-settings/servers/julia-language-server/languageserver.jl:5"," [3] include(::Module, ::String) at ./Base.jl:377"," [4] exec_options(::Base.JLOptions) at ./client.jl:288"," [5] _start() at ./client.jl:484","in expression starting at /Users/home/.local/share/vim-lsp-settings/servers/julia-language-server/languageserver.jl:5",""]]
Wed Jul 15 22:31:11 2020:["s:on_exit",1,"julia-language-server","exited",1]
```

### PR DESCRIPTION
**Pull request by AtsushiSakai**
This PR fix #280 only for *nix 

LanguageServer.jl changed API to launch language server:
https://github.com/julia-vscode/LanguageServer.jl

So, I fixed `install-julia-language-server.sh` based on its official doc.

I checked it works in Mac OS and Ubuntu.
I'm sorry I don't have windows, so I cannot fix `install-julia-language-server.cmd`.

### CODE REVIEW

File: installer/install-julia-language-server.sh [hunk 1]
```diff
@@ -2,25 +2,13 @@
...
-server = LanguageServer.LanguageServerInstance(stdin, stdout, false, envpath)
-server.runlinter = true
-run(server)
-EOF
+julia -e 'using Pkg; Pkg.add("LanguageServer")'
 
 cat <<EOF >julia-language-server
 #!/usr/bin/env bash
 
 DIR=\$(cd \$(dirname \$0); pwd)
```
Comment (mattn) [inline installer/install-julia-language-server.sh:10]: Now $DIR is not required?

Comment (AtsushiSakai) [reply installer/install-julia-language-server.sh]: Sorry. It is not needed. I fixed it.

**Comment by mattn** [comment]
Thank yoi
